### ISSUE TITLE
Dart vs TypeScript

### ISSUE THREAD

**Issue by Nothing-Works** [fChristenson/My-life-as-a-programmer#11]
Hi m8,

I am curious about why Google chose TS over Dart for their Angular at the beginning? now they have Angular Dart for the web as well. As far as I understand Dart can do a lot of things that TS can do. Does it mean that TS is better than Dart? or Ts is easier than Dart for JS developers? And now Flutter is using Dart, as TS does not compile to native code (my understanding). Does it mean Google does not have many other options other than Dart lol. (I mean if TS were possible, they would go with TS)

**Comment by divanvisagie** [comment]
To me it seemed like the plan with Dart was to replace JavaScript not compile to it. I remember when the language was getting started that the team actually had a Dart engine running in a version of Chromium so that you could "run it natively" so the compile to JavaScript feature may have been more of a interim solution while trying to get it to become a browser standard.

As time has gone by though it looks like the language has moved on to providing solutions in other areas at Google, I think they have seen that JavaScript is not going to be replaced so TypeScript is a better option for the web.

**Comment by fChristenson** [comment]
Correct, Dart was designed to replace JavaScript but it never did.

It is hard to reason about every motivation behind a company and it's decisions but often the decisions made are made for a reason that makes sense at that point in time.

For Angular TS is a good pick because Angular is a web framework so adding TS that has seen the best adoption of any JavaScript enhancement language ever is a clever choice but for Flutter things are different.

What would the benefit be of using TS for Flutter? One could argue that it has a bigger fanbase than Dart but is that enough?

TS is useful in of itself but for a non web platform it would make little sense to use it as the language is focused on a different sort of problem and to top it of Google doesn't own TS which has been a bit of an issue for Android and Java as an example.

What I can't figure out is why Dart was picked for Flutter, it is a almost extinct language in IT so I figured that this was an attempt to blow new life in to the language but that is ofc just speculation.
