### ISSUE TITLE
What are some personality traits of a great senior developer?

### ISSUE THREAD

**Issue by kkarlo23** [fChristenson/My-life-as-a-programmer#14]

**Comment by fChristenson** [comment]
Great question!

Since this is quite subjective I will just go with what I have seen some of the best programmers I have worked with and talked to have.

Maturity

They do not act without thinking and they know what to do, how to do it and what the options are.
You will not see a senior be swayed by public opinion or people letting their emotions run wild.
They may bend to someones will but they will speak up and make their point clear.

Organised

As a senior you are a hub of stakeholders, everyones wants to talk to you, juniors, CEO's, customers, PO's, PM's and while all of this is happening a senior needs to deliver on work, plan out work for others, attend meetings, fix bugs, help juniors who are stuck, suggest improvements, help customers and so on.
Having this many responsibilities requires a person who can juggle many things at the same time and not let all the pending work effect their mental state or the quality of their own code.

Inspiring

Seniors have an effect on people, juniors look up to them, stakeholders feel safe when they have them close and companies thrive when they have the right ones.
The best seniors are aware of their position but stay humble, helpful and always try to use their influence to steer things in a better direction.

These are the things I have seen from the people who make a real impact on a place of work and it is why I believe that most people who use the term "senior" have never met one and I feel very fortunate that I have.
