### ISSUE TITLE
What is your opinion about GTP-3?

### ISSUE THREAD

**Issue by StefanSelfTaught** [fChristenson/My-life-as-a-programmer#15]
https://nesslabs.com/gpt-3-future-productivity

**Comment by fChristenson** [comment]
I believe that GPT-3 has a social benefit but what the industry is really after are models they can train for their own company.
Almost every large company these days have a customer satisfaction process and chat bots are on the rise.
It is one of the most sought after cost saving initiatives in IT today to create a automated user support system.
The problem is to train the models and test them effectively for each company.

GPT-3 would be almost useless in this scenario but I believe the next step is to train general models such as GPT-3 and use them as a base that companies can build their own model on top. This would create a even more powerful model.

In the far future it we will likely see companies share their trained models and let other companies use them.
Imagine restaurants or healthcare companies giving out models who are trained to answer food and health questions and you have the start of Skynet.
