### ISSUE TITLE
Can you talk about application programmers?

### ISSUE THREAD

**Issue by gabekus** [fChristenson/My-life-as-a-programmer#4]
Hey Frederik. For the past few years I was confident that I was going to be a full stack developer focused on the back end because I don't really have a sense of design but know how to produce good enough frontend. I recently started interning at a company as an application developer using .NET Core, Vue and Angular, and I really like how the front end just has to be good enough while the main focus of the entire project is to get a working logical application which is what I end up seeing myself doing for a living. I'm not sure how to market myself, would I be a full stack developer, application developer? What are the key differences? Thank you

**Comment by fChristenson** [comment]
Hi Gabe!

In programming there is unfortunately a lot of misuse of terms and people say one thing but mean another thing and these labels have a slightly different meaning depending on who you ask.

What I can tell you is what the industry in general considers each label to be.

A frontend developer is today a person who is considered to be extra good with JavaScript, css and html.

A backend developer is a person who works with web applications and focuses on server side work.

A fullstack developer is a person who can work as both a frontend and backend developer.

A application developer is not a very common term since everything that is user facing is considered a application, a mobile application, desktop application, web application and so on.

What is common however is that people call themselves software developers, this is a umbrella term that basically means "I write code" but it is considered better than calling yourself "programmer" even though they are equal in every practical sense.

The issue some have with the term software developer is that it is too general.

Systems developers, game developers and mobile developers are often considered a minority and their work is very specialised so it is very common that they use their specific titles to express that they aren't web developers while web developers and software developers are often the same thing. 

For you I would go with either software developer or fullstack developer.

Have a great day m8!
